#!/bin/sh

set -- 99 80 40 20 10 5

mkdir -p "${conf_dir:=${XDG_CONFIG_HOME:-$HOME/.config}/spm}/state"

[ -f "$conf_dir/config" ] || {
    printf "(SPM) %s\n" "Please create $conf_dir/config and try again."
    exit 1
}

while :; do
    . "$conf_dir/config"

    read -r batt_status < /sys/class/power_supply/BAT0/status
    read -r batt_percent < /sys/class/power_supply/BAT0/capacity

    case $batt_status in
        Discharging)
            for state in "$@"; do
                if [ "$batt_percent" -le "$state" ]; then
                    [ -f "$conf_dir/state/$state" ] || {
                        rm -f "$conf_dir/state/100"
                        :>"$conf_dir/state/$state"
                        user_custom_low_battery_hook
                    }
                fi
            done
            ;;
        Charging)
            [ -f "$conf_dir/state/100" ] || {
                rm -f "$conf_dir/state"/*
                :> "$conf_dir/state/100"
                user_custom_battery_normal_hook
            }
            ;;
    esac

    sleep 10
done
